// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { evaluateAlerts, getApiAuthCallbackGoogle, getAuthProviders, getDashboard, getDemoDashboard, getDriver, getForecast, getHealth, getMessages, getNearbyStations, getRecommendation, getSession, getTrackedStations, getVehicleLookupAvailability, getWeeklyOutlook, ingestObservations, lookupVehicle, type Options, postApiAuthSignInEmail, postApiAuthSignUpEmail, saveDriver, saveOnboarding, sendPhoneOtp, signInWithGoogle, signOut, syncData, updateTank, updateTrackedStations, verifyPhoneOtp } from '../sdk.gen';
import type { EvaluateAlertsData, EvaluateAlertsError, EvaluateAlertsResponse, GetApiAuthCallbackGoogleData, GetAuthProvidersData, GetAuthProvidersResponse, GetDashboardData, GetDashboardError, GetDashboardResponse, GetDemoDashboardData, GetDemoDashboardError, GetDemoDashboardResponse, GetDriverData, GetDriverError, GetDriverResponse, GetForecastData, GetForecastError, GetForecastResponse, GetHealthData, GetHealthResponse, GetMessagesData, GetMessagesError, GetMessagesResponse, GetNearbyStationsData, GetNearbyStationsError, GetNearbyStationsResponse, GetRecommendationData, GetRecommendationError, GetRecommendationResponse, GetSessionData, GetTrackedStationsData, GetTrackedStationsError, GetTrackedStationsResponse, GetVehicleLookupAvailabilityData, GetVehicleLookupAvailabilityError, GetVehicleLookupAvailabilityResponse, GetWeeklyOutlookData, GetWeeklyOutlookError, GetWeeklyOutlookResponse, IngestObservationsData, IngestObservationsError, IngestObservationsResponse, LookupVehicleData, LookupVehicleError, LookupVehicleResponse, PostApiAuthSignInEmailData, PostApiAuthSignInEmailError, PostApiAuthSignUpEmailData, PostApiAuthSignUpEmailError, SaveDriverData, SaveDriverError, SaveDriverResponse, SaveOnboardingData, SaveOnboardingError, SaveOnboardingResponse, SendPhoneOtpData, SendPhoneOtpError, SendPhoneOtpResponse, SignInWithGoogleData, SignInWithGoogleError, SignInWithGoogleResponse, SignOutData, SignOutResponse, SyncDataData, SyncDataError, SyncDataResponse, UpdateTankData, UpdateTankError, UpdateTankResponse, UpdateTrackedStationsData, UpdateTrackedStationsError, UpdateTrackedStationsResponse, VerifyPhoneOtpData, VerifyPhoneOtpError, VerifyPhoneOtpResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

export const getHealthOptions = (options?: Options<GetHealthData>) => queryOptions<GetHealthResponse, DefaultError, GetHealthResponse, ReturnType<typeof getHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthQueryKey(options)
});

export const getForecastQueryKey = (options?: Options<GetForecastData>) => createQueryKey('getForecast', options);

/**
 * Get a 14-day petrol-price scenario
 */
export const getForecastOptions = (options?: Options<GetForecastData>) => queryOptions<GetForecastResponse, GetForecastError, GetForecastResponse, ReturnType<typeof getForecastQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getForecast({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getForecastQueryKey(options)
});

export const getDemoDashboardQueryKey = (options?: Options<GetDemoDashboardData>) => createQueryKey('getDemoDashboard', options);

/**
 * Explore a synthetic example driver and forecast
 */
export const getDemoDashboardOptions = (options?: Options<GetDemoDashboardData>) => queryOptions<GetDemoDashboardResponse, GetDemoDashboardError, GetDemoDashboardResponse, ReturnType<typeof getDemoDashboardQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDemoDashboard({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDemoDashboardQueryKey(options)
});

export const getDriverQueryKey = (options?: Options<GetDriverData>) => createQueryKey('getDriver', options);

export const getDriverOptions = (options?: Options<GetDriverData>) => queryOptions<GetDriverResponse, GetDriverError, GetDriverResponse, ReturnType<typeof getDriverQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDriver({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDriverQueryKey(options)
});

/**
 * Set car, current tank reading, and SMS consent
 *
 * PUT replaces the car and confirms a fresh tank reading at the server time. Send the current gauge reading, not an old stored value. smsEnabled is explicit consent; set false to opt out.
 */
export const saveDriverMutation = (options?: Partial<Options<SaveDriverData>>): UseMutationOptions<SaveDriverResponse, SaveDriverError, Options<SaveDriverData>> => {
    const mutationOptions: UseMutationOptions<SaveDriverResponse, SaveDriverError, Options<SaveDriverData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await saveDriver({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getDashboardQueryKey = (options?: Options<GetDashboardData>) => createQueryKey('getDashboard', options);

export const getDashboardOptions = (options?: Options<GetDashboardData>) => queryOptions<GetDashboardResponse, GetDashboardError, GetDashboardResponse, ReturnType<typeof getDashboardQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDashboard({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDashboardQueryKey(options)
});

export const getRecommendationQueryKey = (options?: Options<GetRecommendationData>) => createQueryKey('getRecommendation', options);

export const getRecommendationOptions = (options?: Options<GetRecommendationData>) => queryOptions<GetRecommendationResponse, GetRecommendationError, GetRecommendationResponse, ReturnType<typeof getRecommendationQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRecommendation({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRecommendationQueryKey(options)
});

export const getMessagesQueryKey = (options?: Options<GetMessagesData>) => createQueryKey('getMessages', options);

export const getMessagesOptions = (options?: Options<GetMessagesData>) => queryOptions<GetMessagesResponse, GetMessagesError, GetMessagesResponse, ReturnType<typeof getMessagesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMessages({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMessagesQueryKey(options)
});

/**
 * Import GBP refined petrol observations
 */
export const ingestObservationsMutation = (options?: Partial<Options<IngestObservationsData>>): UseMutationOptions<IngestObservationsResponse, IngestObservationsError, Options<IngestObservationsData>> => {
    const mutationOptions: UseMutationOptions<IngestObservationsResponse, IngestObservationsError, Options<IngestObservationsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ingestObservations({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Evaluate opted-in users (scheduler/manual operations)
 */
export const evaluateAlertsMutation = (options?: Partial<Options<EvaluateAlertsData>>): UseMutationOptions<EvaluateAlertsResponse, EvaluateAlertsError, Options<EvaluateAlertsData>> => {
    const mutationOptions: UseMutationOptions<EvaluateAlertsResponse, EvaluateAlertsError, Options<EvaluateAlertsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await evaluateAlerts({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getVehicleLookupAvailabilityQueryKey = (options?: Options<GetVehicleLookupAvailabilityData>) => createQueryKey('getVehicleLookupAvailability', options);

/**
 * Check whether registration lookup is available
 */
export const getVehicleLookupAvailabilityOptions = (options?: Options<GetVehicleLookupAvailabilityData>) => queryOptions<GetVehicleLookupAvailabilityResponse, GetVehicleLookupAvailabilityError, GetVehicleLookupAvailabilityResponse, ReturnType<typeof getVehicleLookupAvailabilityQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getVehicleLookupAvailability({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getVehicleLookupAvailabilityQueryKey(options)
});

/**
 * Look up car specifications by UK registration
 *
 * Uses UK Vehicle Data via One Auto API. Maximum 10 attempts per user per UTC day. Registration is sent in the body and is not stored. Tank capacity and combined imperial MPG can be missing; users must review specifications before saving. No automatic retries.
 */
export const lookupVehicleMutation = (options?: Partial<Options<LookupVehicleData>>): UseMutationOptions<LookupVehicleResponse, LookupVehicleError, Options<LookupVehicleData>> => {
    const mutationOptions: UseMutationOptions<LookupVehicleResponse, LookupVehicleError, Options<LookupVehicleData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await lookupVehicle({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getNearbyStationsQueryKey = (options: Options<GetNearbyStationsData>) => createQueryKey('getNearbyStations', options);

/**
 * Find E10 petrol stations within five miles
 *
 * Current stored Fuel Finder prices, refreshed hourly. Coordinates are used for this search and are not stored in your profile.
 */
export const getNearbyStationsOptions = (options: Options<GetNearbyStationsData>) => queryOptions<GetNearbyStationsResponse, GetNearbyStationsError, GetNearbyStationsResponse, ReturnType<typeof getNearbyStationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getNearbyStations({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getNearbyStationsQueryKey(options)
});

export const getTrackedStationsQueryKey = (options?: Options<GetTrackedStationsData>) => createQueryKey('getTrackedStations', options);

/**
 * Tracked stations and up to 30 days of actual hourly observations
 */
export const getTrackedStationsOptions = (options?: Options<GetTrackedStationsData>) => queryOptions<GetTrackedStationsResponse, GetTrackedStationsError, GetTrackedStationsResponse, ReturnType<typeof getTrackedStationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTrackedStations({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTrackedStationsQueryKey(options)
});

/**
 * Change tracked stations without resetting the tank reading or car details
 */
export const updateTrackedStationsMutation = (options?: Partial<Options<UpdateTrackedStationsData>>): UseMutationOptions<UpdateTrackedStationsResponse, UpdateTrackedStationsError, Options<UpdateTrackedStationsData>> => {
    const mutationOptions: UseMutationOptions<UpdateTrackedStationsResponse, UpdateTrackedStationsError, Options<UpdateTrackedStationsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateTrackedStations({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Save car, weekly mileage and one to three nearby stations atomically
 */
export const saveOnboardingMutation = (options?: Partial<Options<SaveOnboardingData>>): UseMutationOptions<SaveOnboardingResponse, SaveOnboardingError, Options<SaveOnboardingData>> => {
    const mutationOptions: UseMutationOptions<SaveOnboardingResponse, SaveOnboardingError, Options<SaveOnboardingData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await saveOnboarding({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Record your current gauge without changing your car or driving schedule
 */
export const updateTankMutation = (options?: Partial<Options<UpdateTankData>>): UseMutationOptions<UpdateTankResponse, UpdateTankError, Options<UpdateTankData>> => {
    const mutationOptions: UseMutationOptions<UpdateTankResponse, UpdateTankError, Options<UpdateTankData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateTank({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Run daily market or hourly station ingestion
 *
 * Idempotent across Workers using Postgres job claims. Daily downloads run at most once per UTC day; hourly station collection runs at most once per UTC hour. Failed attempts remain recorded and retry next scheduled period.
 */
export const syncDataMutation = (options?: Partial<Options<SyncDataData>>): UseMutationOptions<SyncDataResponse, SyncDataError, Options<SyncDataData>> => {
    const mutationOptions: UseMutationOptions<SyncDataResponse, SyncDataError, Options<SyncDataData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await syncData({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAuthProvidersQueryKey = (options?: Options<GetAuthProvidersData>) => createQueryKey('getAuthProviders', options);

/**
 * Discover sign-in methods enabled on this server
 */
export const getAuthProvidersOptions = (options?: Options<GetAuthProvidersData>) => queryOptions<GetAuthProvidersResponse, DefaultError, GetAuthProvidersResponse, ReturnType<typeof getAuthProvidersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAuthProviders({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAuthProvidersQueryKey(options)
});

/**
 * Send a sign-in code to a UK mobile
 *
 * Available only with all three Twilio Verify credentials. Retain Better Auth cookies (or use its Expo client on native). Codes are checked and consumed by Twilio. Per-number limits: 3 sends and 10 checks per 10 minutes, plus IP limits and Twilio protections. Does not enable SMS alerts or link an existing Google account. Phone/password and password-reset routes are not exposed.
 */
export const sendPhoneOtpMutation = (options?: Partial<Options<SendPhoneOtpData>>): UseMutationOptions<SendPhoneOtpResponse, SendPhoneOtpError, Options<SendPhoneOtpData>> => {
    const mutationOptions: UseMutationOptions<SendPhoneOtpResponse, SendPhoneOtpError, Options<SendPhoneOtpData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await sendPhoneOtp({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Verify an SMS code and sign in or create an account
 *
 * Available only with all three Twilio Verify credentials. Retain Better Auth cookies (or use its Expo client on native). Codes are checked and consumed by Twilio. Per-number limits: 3 sends and 10 checks per 10 minutes, plus IP limits and Twilio protections. Does not enable SMS alerts or link an existing Google account. Phone/password and password-reset routes are not exposed.
 */
export const verifyPhoneOtpMutation = (options?: Partial<Options<VerifyPhoneOtpData>>): UseMutationOptions<VerifyPhoneOtpResponse, VerifyPhoneOtpError, Options<VerifyPhoneOtpData>> => {
    const mutationOptions: UseMutationOptions<VerifyPhoneOtpResponse, VerifyPhoneOtpError, Options<VerifyPhoneOtpData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await verifyPhoneOtp({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getWeeklyOutlookQueryKey = (options?: Options<GetWeeklyOutlookData>) => createQueryKey('getWeeklyOutlook', options);

/**
 * Official sales-weighted UK weekly petrol outlook
 */
export const getWeeklyOutlookOptions = (options?: Options<GetWeeklyOutlookData>) => queryOptions<GetWeeklyOutlookResponse, GetWeeklyOutlookError, GetWeeklyOutlookResponse, ReturnType<typeof getWeeklyOutlookQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getWeeklyOutlook({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWeeklyOutlookQueryKey(options)
});

/**
 * Start Google sign-in or account creation
 *
 * Better Auth manages OAuth state, PKCE and the session cookie. Follow the returned authorization URL in the browser. Callback URLs must use APP_ORIGIN.
 */
export const signInWithGoogleMutation = (options?: Partial<Options<SignInWithGoogleData>>): UseMutationOptions<SignInWithGoogleResponse, SignInWithGoogleError, Options<SignInWithGoogleData>> => {
    const mutationOptions: UseMutationOptions<SignInWithGoogleResponse, SignInWithGoogleError, Options<SignInWithGoogleData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await signInWithGoogle({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create a local development account
 *
 * Available only when the server ENVIRONMENT is development. Returns 404 in production and test. Better Auth hashes passwords, validates origins and issues the normal session cookie; no verification email is sent. Native clients use the Better Auth Expo SDK.
 */
export const postApiAuthSignUpEmailMutation = (options?: Partial<Options<PostApiAuthSignUpEmailData>>): UseMutationOptions<unknown, PostApiAuthSignUpEmailError, Options<PostApiAuthSignUpEmailData>> => {
    const mutationOptions: UseMutationOptions<unknown, PostApiAuthSignUpEmailError, Options<PostApiAuthSignUpEmailData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiAuthSignUpEmail({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Sign in to a local development account
 *
 * Available only when the server ENVIRONMENT is development. Returns 404 in production and test. Better Auth hashes passwords, validates origins and issues the normal session cookie; no verification email is sent. Native clients use the Better Auth Expo SDK.
 */
export const postApiAuthSignInEmailMutation = (options?: Partial<Options<PostApiAuthSignInEmailData>>): UseMutationOptions<unknown, PostApiAuthSignInEmailError, Options<PostApiAuthSignInEmailData>> => {
    const mutationOptions: UseMutationOptions<unknown, PostApiAuthSignInEmailError, Options<PostApiAuthSignInEmailData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiAuthSignInEmail({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiAuthCallbackGoogleQueryKey = (options?: Options<GetApiAuthCallbackGoogleData>) => createQueryKey('getApiAuthCallbackGoogle', options);

/**
 * Google OAuth callback (managed by Better Auth)
 */
export const getApiAuthCallbackGoogleOptions = (options?: Options<GetApiAuthCallbackGoogleData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiAuthCallbackGoogleQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiAuthCallbackGoogle({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiAuthCallbackGoogleQueryKey(options)
});

export const getSessionQueryKey = (options?: Options<GetSessionData>) => createQueryKey('getSession', options);

export const getSessionOptions = (options?: Options<GetSessionData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getSessionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSession({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSessionQueryKey(options)
});

export const signOutMutation = (options?: Partial<Options<SignOutData>>): UseMutationOptions<SignOutResponse, DefaultError, Options<SignOutData>> => {
    const mutationOptions: UseMutationOptions<SignOutResponse, DefaultError, Options<SignOutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await signOut({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
