// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { EvaluateAlertsData, EvaluateAlertsErrors, EvaluateAlertsResponses, GetApiAuthCallbackGoogleData, GetDashboardData, GetDashboardErrors, GetDashboardResponses, GetDemoDashboardData, GetDemoDashboardErrors, GetDemoDashboardResponses, GetDriverData, GetDriverErrors, GetDriverResponses, GetForecastData, GetForecastErrors, GetForecastResponses, GetHealthData, GetHealthResponses, GetMessagesData, GetMessagesErrors, GetMessagesResponses, GetNearbyStationsData, GetNearbyStationsErrors, GetNearbyStationsResponses, GetRecommendationData, GetRecommendationErrors, GetRecommendationResponses, GetSessionData, GetSessionResponses, GetTrackedStationsData, GetTrackedStationsErrors, GetTrackedStationsResponses, GetVehicleLookupAvailabilityData, GetVehicleLookupAvailabilityErrors, GetVehicleLookupAvailabilityResponses, GetWeeklyOutlookData, GetWeeklyOutlookErrors, GetWeeklyOutlookResponses, IngestObservationsData, IngestObservationsErrors, IngestObservationsResponses, LookupVehicleData, LookupVehicleErrors, LookupVehicleResponses, SaveDriverData, SaveDriverErrors, SaveDriverResponses, SaveOnboardingData, SaveOnboardingErrors, SaveOnboardingResponses, SignInWithGoogleData, SignInWithGoogleErrors, SignInWithGoogleResponses, SignOutData, SignOutResponses, SyncDataData, SyncDataErrors, SyncDataResponses, UpdateTankData, UpdateTankErrors, UpdateTankResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * Get a 14-day petrol-price scenario
 */
export const getForecast = <ThrowOnError extends boolean = false>(options?: Options<GetForecastData, ThrowOnError>): RequestResult<GetForecastResponses, GetForecastErrors, ThrowOnError> => (options?.client ?? client).get<GetForecastResponses, GetForecastErrors, ThrowOnError>({ url: '/api/v1/forecast', ...options });

/**
 * Explore a synthetic example driver and forecast
 */
export const getDemoDashboard = <ThrowOnError extends boolean = false>(options?: Options<GetDemoDashboardData, ThrowOnError>): RequestResult<GetDemoDashboardResponses, GetDemoDashboardErrors, ThrowOnError> => (options?.client ?? client).get<GetDemoDashboardResponses, GetDemoDashboardErrors, ThrowOnError>({ url: '/api/v1/demo', ...options });

export const getDriver = <ThrowOnError extends boolean = false>(options?: Options<GetDriverData, ThrowOnError>): RequestResult<GetDriverResponses, GetDriverErrors, ThrowOnError> => (options?.client ?? client).get<GetDriverResponses, GetDriverErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/driver',
    ...options
});

/**
 * Set car, current tank reading, and SMS consent
 *
 * PUT replaces the car and confirms a fresh tank reading at the server time. Send the current gauge reading, not an old stored value. smsEnabled is explicit consent; set false to opt out.
 */
export const saveDriver = <ThrowOnError extends boolean = false>(options: Options<SaveDriverData, ThrowOnError>): RequestResult<SaveDriverResponses, SaveDriverErrors, ThrowOnError> => (options.client ?? client).put<SaveDriverResponses, SaveDriverErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/driver',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getDashboard = <ThrowOnError extends boolean = false>(options?: Options<GetDashboardData, ThrowOnError>): RequestResult<GetDashboardResponses, GetDashboardErrors, ThrowOnError> => (options?.client ?? client).get<GetDashboardResponses, GetDashboardErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/dashboard',
    ...options
});

export const getRecommendation = <ThrowOnError extends boolean = false>(options?: Options<GetRecommendationData, ThrowOnError>): RequestResult<GetRecommendationResponses, GetRecommendationErrors, ThrowOnError> => (options?.client ?? client).get<GetRecommendationResponses, GetRecommendationErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/recommendation',
    ...options
});

export const getMessages = <ThrowOnError extends boolean = false>(options?: Options<GetMessagesData, ThrowOnError>): RequestResult<GetMessagesResponses, GetMessagesErrors, ThrowOnError> => (options?.client ?? client).get<GetMessagesResponses, GetMessagesErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/messages',
    ...options
});

/**
 * Import GBP refined petrol observations
 */
export const ingestObservations = <ThrowOnError extends boolean = false>(options: Options<IngestObservationsData, ThrowOnError>): RequestResult<IngestObservationsResponses, IngestObservationsErrors, ThrowOnError> => (options.client ?? client).post<IngestObservationsResponses, IngestObservationsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/market/observations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Evaluate opted-in users (scheduler/manual operations)
 */
export const evaluateAlerts = <ThrowOnError extends boolean = false>(options?: Options<EvaluateAlertsData, ThrowOnError>): RequestResult<EvaluateAlertsResponses, EvaluateAlertsErrors, ThrowOnError> => (options?.client ?? client).post<EvaluateAlertsResponses, EvaluateAlertsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/alerts/evaluate',
    ...options
});

/**
 * Check whether registration lookup is available
 */
export const getVehicleLookupAvailability = <ThrowOnError extends boolean = false>(options?: Options<GetVehicleLookupAvailabilityData, ThrowOnError>): RequestResult<GetVehicleLookupAvailabilityResponses, GetVehicleLookupAvailabilityErrors, ThrowOnError> => (options?.client ?? client).get<GetVehicleLookupAvailabilityResponses, GetVehicleLookupAvailabilityErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/vehicle-lookup',
    ...options
});

/**
 * Look up car specifications by UK registration
 *
 * Uses UK Vehicle Data via One Auto API. Maximum 10 attempts per user per UTC day. Registration is sent in the body and is not stored. Tank capacity and combined imperial MPG can be missing; users must review specifications before saving. No automatic retries.
 */
export const lookupVehicle = <ThrowOnError extends boolean = false>(options: Options<LookupVehicleData, ThrowOnError>): RequestResult<LookupVehicleResponses, LookupVehicleErrors, ThrowOnError> => (options.client ?? client).post<LookupVehicleResponses, LookupVehicleErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/vehicle-lookup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Find E10 petrol stations within five miles
 *
 * Current stored Fuel Finder prices, refreshed hourly. Coordinates are used for this search and are not stored in your profile.
 */
export const getNearbyStations = <ThrowOnError extends boolean = false>(options: Options<GetNearbyStationsData, ThrowOnError>): RequestResult<GetNearbyStationsResponses, GetNearbyStationsErrors, ThrowOnError> => (options.client ?? client).get<GetNearbyStationsResponses, GetNearbyStationsErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/stations/nearby',
    ...options
});

/**
 * Tracked stations and up to 30 days of actual hourly observations
 */
export const getTrackedStations = <ThrowOnError extends boolean = false>(options?: Options<GetTrackedStationsData, ThrowOnError>): RequestResult<GetTrackedStationsResponses, GetTrackedStationsErrors, ThrowOnError> => (options?.client ?? client).get<GetTrackedStationsResponses, GetTrackedStationsErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/stations',
    ...options
});

/**
 * Save car, weekly mileage and one to three nearby stations atomically
 */
export const saveOnboarding = <ThrowOnError extends boolean = false>(options: Options<SaveOnboardingData, ThrowOnError>): RequestResult<SaveOnboardingResponses, SaveOnboardingErrors, ThrowOnError> => (options.client ?? client).put<SaveOnboardingResponses, SaveOnboardingErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/onboarding',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Record your current gauge without changing your car or driving schedule
 */
export const updateTank = <ThrowOnError extends boolean = false>(options: Options<UpdateTankData, ThrowOnError>): RequestResult<UpdateTankResponses, UpdateTankErrors, ThrowOnError> => (options.client ?? client).patch<UpdateTankResponses, UpdateTankErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/tank',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Run daily market or hourly station ingestion
 *
 * Idempotent across Workers using Postgres job claims. Daily downloads run at most once per UTC day; hourly station collection runs at most once per UTC hour. Failed attempts remain recorded and retry next scheduled period.
 */
export const syncData = <ThrowOnError extends boolean = false>(options: Options<SyncDataData, ThrowOnError>): RequestResult<SyncDataResponses, SyncDataErrors, ThrowOnError> => (options.client ?? client).post<SyncDataResponses, SyncDataErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/data/sync/{kind}',
    ...options
});

/**
 * Official sales-weighted UK weekly petrol outlook
 */
export const getWeeklyOutlook = <ThrowOnError extends boolean = false>(options?: Options<GetWeeklyOutlookData, ThrowOnError>): RequestResult<GetWeeklyOutlookResponses, GetWeeklyOutlookErrors, ThrowOnError> => (options?.client ?? client).get<GetWeeklyOutlookResponses, GetWeeklyOutlookErrors, ThrowOnError>({ url: '/api/v1/forecast/weekly', ...options });

/**
 * Start Google sign-in or account creation
 *
 * Better Auth manages OAuth state, PKCE and the session cookie. Follow the returned authorization URL in the browser. Callback URLs must use APP_ORIGIN.
 */
export const signInWithGoogle = <ThrowOnError extends boolean = false>(options: Options<SignInWithGoogleData, ThrowOnError>): RequestResult<SignInWithGoogleResponses, SignInWithGoogleErrors, ThrowOnError> => (options.client ?? client).post<SignInWithGoogleResponses, SignInWithGoogleErrors, ThrowOnError>({
    url: '/api/auth/sign-in/social',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Google OAuth callback (managed by Better Auth)
 */
export const getApiAuthCallbackGoogle = <ThrowOnError extends boolean = false>(options?: Options<GetApiAuthCallbackGoogleData, ThrowOnError>): RequestResult<unknown, unknown, ThrowOnError> => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/api/auth/callback/google', ...options });

export const getSession = <ThrowOnError extends boolean = false>(options?: Options<GetSessionData, ThrowOnError>): RequestResult<GetSessionResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetSessionResponses, unknown, ThrowOnError>({ url: '/api/auth/get-session', ...options });

export const signOut = <ThrowOnError extends boolean = false>(options?: Options<SignOutData, ThrowOnError>): RequestResult<SignOutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<SignOutResponses, unknown, ThrowOnError>({ url: '/api/auth/sign-out', ...options });
