// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { EvaluateAlertsData, EvaluateAlertsErrors, EvaluateAlertsResponses, GetDashboardData, GetDashboardErrors, GetDashboardResponses, GetDemoDashboardData, GetDemoDashboardErrors, GetDemoDashboardResponses, GetDriverData, GetDriverErrors, GetDriverResponses, GetForecastData, GetForecastErrors, GetForecastResponses, GetHealthData, GetHealthResponses, GetMessagesData, GetMessagesErrors, GetMessagesResponses, GetNearbyStationsData, GetNearbyStationsErrors, GetNearbyStationsResponses, GetRecommendationData, GetRecommendationErrors, GetRecommendationResponses, GetSessionData, GetSessionResponses, GetTrackedStationsData, GetTrackedStationsErrors, GetTrackedStationsResponses, IngestObservationsData, IngestObservationsErrors, IngestObservationsResponses, SaveDriverData, SaveDriverErrors, SaveDriverResponses, SaveOnboardingData, SaveOnboardingErrors, SaveOnboardingResponses, SendPhoneOtpData, SendPhoneOtpErrors, SendPhoneOtpResponses, SignOutData, SignOutResponses, SyncDataData, SyncDataErrors, SyncDataResponses, UpdateTankData, UpdateTankErrors, UpdateTankResponses, VerifyPhoneOtpData, VerifyPhoneOtpErrors, VerifyPhoneOtpResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * Get a 14-day petrol-price scenario
 */
export const getForecast = <ThrowOnError extends boolean = false>(options?: Options<GetForecastData, ThrowOnError>): RequestResult<GetForecastResponses, GetForecastErrors, ThrowOnError> => (options?.client ?? client).get<GetForecastResponses, GetForecastErrors, ThrowOnError>({ url: '/api/v1/forecast', ...options });

/**
 * Explore a synthetic example driver and forecast
 */
export const getDemoDashboard = <ThrowOnError extends boolean = false>(options?: Options<GetDemoDashboardData, ThrowOnError>): RequestResult<GetDemoDashboardResponses, GetDemoDashboardErrors, ThrowOnError> => (options?.client ?? client).get<GetDemoDashboardResponses, GetDemoDashboardErrors, ThrowOnError>({ url: '/api/v1/demo', ...options });

export const getDriver = <ThrowOnError extends boolean = false>(options?: Options<GetDriverData, ThrowOnError>): RequestResult<GetDriverResponses, GetDriverErrors, ThrowOnError> => (options?.client ?? client).get<GetDriverResponses, GetDriverErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/driver',
    ...options
});

/**
 * Set car, current tank reading, and SMS consent
 *
 * PUT replaces the car and confirms a fresh tank reading at the server time. Send the current gauge reading, not an old stored value. smsEnabled is explicit consent; set false to opt out.
 */
export const saveDriver = <ThrowOnError extends boolean = false>(options: Options<SaveDriverData, ThrowOnError>): RequestResult<SaveDriverResponses, SaveDriverErrors, ThrowOnError> => (options.client ?? client).put<SaveDriverResponses, SaveDriverErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/driver',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getDashboard = <ThrowOnError extends boolean = false>(options?: Options<GetDashboardData, ThrowOnError>): RequestResult<GetDashboardResponses, GetDashboardErrors, ThrowOnError> => (options?.client ?? client).get<GetDashboardResponses, GetDashboardErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/dashboard',
    ...options
});

export const getRecommendation = <ThrowOnError extends boolean = false>(options?: Options<GetRecommendationData, ThrowOnError>): RequestResult<GetRecommendationResponses, GetRecommendationErrors, ThrowOnError> => (options?.client ?? client).get<GetRecommendationResponses, GetRecommendationErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/recommendation',
    ...options
});

export const getMessages = <ThrowOnError extends boolean = false>(options?: Options<GetMessagesData, ThrowOnError>): RequestResult<GetMessagesResponses, GetMessagesErrors, ThrowOnError> => (options?.client ?? client).get<GetMessagesResponses, GetMessagesErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/messages',
    ...options
});

/**
 * Import GBP refined petrol observations
 */
export const ingestObservations = <ThrowOnError extends boolean = false>(options: Options<IngestObservationsData, ThrowOnError>): RequestResult<IngestObservationsResponses, IngestObservationsErrors, ThrowOnError> => (options.client ?? client).post<IngestObservationsResponses, IngestObservationsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/market/observations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Evaluate opted-in users (scheduler/manual operations)
 */
export const evaluateAlerts = <ThrowOnError extends boolean = false>(options?: Options<EvaluateAlertsData, ThrowOnError>): RequestResult<EvaluateAlertsResponses, EvaluateAlertsErrors, ThrowOnError> => (options?.client ?? client).post<EvaluateAlertsResponses, EvaluateAlertsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/alerts/evaluate',
    ...options
});

/**
 * Find E10 petrol stations within five miles
 *
 * Current stored Fuel Finder prices, refreshed hourly. Coordinates are used for this search and are not stored in your profile.
 */
export const getNearbyStations = <ThrowOnError extends boolean = false>(options: Options<GetNearbyStationsData, ThrowOnError>): RequestResult<GetNearbyStationsResponses, GetNearbyStationsErrors, ThrowOnError> => (options.client ?? client).get<GetNearbyStationsResponses, GetNearbyStationsErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/stations/nearby',
    ...options
});

/**
 * Tracked stations and up to 30 days of actual hourly observations
 */
export const getTrackedStations = <ThrowOnError extends boolean = false>(options?: Options<GetTrackedStationsData, ThrowOnError>): RequestResult<GetTrackedStationsResponses, GetTrackedStationsErrors, ThrowOnError> => (options?.client ?? client).get<GetTrackedStationsResponses, GetTrackedStationsErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/stations',
    ...options
});

/**
 * Save car, weekly mileage and one to three nearby stations atomically
 */
export const saveOnboarding = <ThrowOnError extends boolean = false>(options: Options<SaveOnboardingData, ThrowOnError>): RequestResult<SaveOnboardingResponses, SaveOnboardingErrors, ThrowOnError> => (options.client ?? client).put<SaveOnboardingResponses, SaveOnboardingErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/onboarding',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Record your current gauge without changing your car or driving schedule
 */
export const updateTank = <ThrowOnError extends boolean = false>(options: Options<UpdateTankData, ThrowOnError>): RequestResult<UpdateTankResponses, UpdateTankErrors, ThrowOnError> => (options.client ?? client).patch<UpdateTankResponses, UpdateTankErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'better-auth.session_token',
            type: 'apiKey'
        }],
    url: '/api/v1/me/tank',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Run daily market or hourly station ingestion
 *
 * Idempotent across Workers using Postgres job claims. Daily downloads run at most once per UTC day; hourly station collection runs at most once per UTC hour. Failed attempts remain recorded and retry next scheduled period.
 */
export const syncData = <ThrowOnError extends boolean = false>(options: Options<SyncDataData, ThrowOnError>): RequestResult<SyncDataResponses, SyncDataErrors, ThrowOnError> => (options.client ?? client).post<SyncDataResponses, SyncDataErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/data/sync/{kind}',
    ...options
});

/**
 * Send a six-digit phone verification code
 */
export const sendPhoneOtp = <ThrowOnError extends boolean = false>(options: Options<SendPhoneOtpData, ThrowOnError>): RequestResult<SendPhoneOtpResponses, SendPhoneOtpErrors, ThrowOnError> => (options.client ?? client).post<SendPhoneOtpResponses, SendPhoneOtpErrors, ThrowOnError>({
    url: '/api/auth/phone-number/send-otp',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Verify code; create account or sign in and set the session cookie
 */
export const verifyPhoneOtp = <ThrowOnError extends boolean = false>(options: Options<VerifyPhoneOtpData, ThrowOnError>): RequestResult<VerifyPhoneOtpResponses, VerifyPhoneOtpErrors, ThrowOnError> => (options.client ?? client).post<VerifyPhoneOtpResponses, VerifyPhoneOtpErrors, ThrowOnError>({
    url: '/api/auth/phone-number/verify',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getSession = <ThrowOnError extends boolean = false>(options?: Options<GetSessionData, ThrowOnError>): RequestResult<GetSessionResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetSessionResponses, unknown, ThrowOnError>({ url: '/api/auth/get-session', ...options });

export const signOut = <ThrowOnError extends boolean = false>(options?: Options<SignOutData, ThrowOnError>): RequestResult<SignOutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<SignOutResponses, unknown, ThrowOnError>({ url: '/api/auth/sign-out', ...options });
