// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Forecast = {
    asOf: string;
    generatedAt: string;
    source: string;
    mode: 'demo' | 'live' | 'sample';
    model?: 'daily-ridge' | 'heuristic';
    modelVersion?: string;
    adviceHorizonDays?: number;
    snapshotAt?: string;
    series?: string;
    openStationPricePence?: number | null;
    fuelType: 'petrol';
    currency: 'GBP';
    unit: 'pence/litre';
    currentPricePence: number;
    wholesalePence: number | null;
    wholesaleChangePercent: number | null;
    usdPerGbp: number | null;
    direction: 'falling' | 'rising' | 'steady';
    signal: 'falling' | 'rising' | 'disruption' | 'fx-shock' | 'steady';
    consecutiveFallingDays: number;
    history: Array<{
        date: string;
        pricePence: number;
        wholesalePence: number | null;
        source?: 'fuel-finder' | 'sample';
    }>;
    points: Array<{
        date: string;
        pricePence: number;
        lowPence: number;
        highPence: number;
        confidence?: 'low' | 'medium';
        signals?: Array<{
            name: 'pump' | 'b7h' | 'crude' | 'baseline';
            label: string;
            weight?: number;
            contributionPence: number;
            detail: string;
            available: boolean;
        }>;
    }>;
    explanation: string;
    methodology: string;
    warnings: Array<string>;
};

export type ApiError = {
    error: {
        code: string;
        message: string;
    };
};

export type Dashboard = {
    driver: Driver;
    forecast: Forecast & ({
        [key: string]: unknown;
    } | null);
    recommendation: Recommendation;
    forecastError?: string;
};

export type Driver = {
    vehicleName?: string;
    tankCapacityLitres: number;
    currentLitres: number;
    /**
     * UK imperial miles per gallon
     */
    mpg: number;
    dailyMiles: number;
    smsEnabled: boolean;
    mileageMode?: 'average' | 'weekly';
    /**
     * Monday through Sunday
     */
    weekdayMiles?: Array<number>;
    onboardingComplete?: boolean;
    fuelUpdatedAt: string;
    updatedAt: string;
};

export type Recommendation = {
    action: 'wait' | 'top-up' | 'fill-now' | 'hold' | 'update-tank';
    title: string;
    reason: string;
    litresToBuy: number;
    estimatedCostGbp: number;
    estimatedSavingsGbp: number;
    fillDate: string;
    nextFillDate: string;
    estimatedCurrentLitres: number;
    reserveLitres: number;
    daysOfFuel: number | null;
    targetPricePence: number;
    tips: Array<string>;
} | null;

export type DriverInput = {
    vehicleName?: string;
    tankCapacityLitres: number;
    currentLitres: number;
    /**
     * UK imperial miles per gallon
     */
    mpg: number;
    dailyMiles: number;
    smsEnabled: boolean;
    mileageMode?: 'average' | 'weekly';
    /**
     * Monday through Sunday
     */
    weekdayMiles?: Array<number>;
};

export type SmsMessage = {
    id: string;
    kind: 'otp' | 'fill-alert';
    body: string;
    status: 'pending' | 'stubbed' | 'failed';
    createdAt: string;
};

export type MarketIngestion = {
    source: string;
    observations: Array<MarketObservation>;
};

export type MarketObservation = {
    date: string;
    /**
     * Refined petrol wholesale price in GBP pence/litre
     */
    wholesalePence: number;
    retailPence: number;
    usdPerGbp: number;
    disruption?: boolean;
};

export type NearbyStations = {
    stations: Array<Station>;
    radiusMiles: 5;
    checkedAt: string | null;
};

export type Station = {
    id: string;
    name: string;
    brand: string;
    address: string;
    postcode: string;
    latitude: number;
    longitude: number;
    motorway: boolean;
    closed: boolean;
    pricePence: number | null;
    priceUpdatedAt: string | null;
    checkedAt: string | null;
    distanceMiles?: number;
};

export type TrackedStations = {
    stations: Array<Station & {
        history: Array<{
            observedAt: string;
            pricePence: number;
        }>;
    }>;
    since: string;
};

export type OnboardingInput = {
    driver: DriverInput;
    location: {
        latitude: number;
        longitude: number;
    };
    stationIds: Array<string>;
};

export type TankInput = {
    currentLitres: number;
};

export type WeeklyOutlook = {
    model: 'weekly-huber';
    modelVersion: string;
    generatedAt: string;
    issuedAt: string;
    referenceDate: string;
    series: 'Official DESNZ sales-weighted petrol';
    unit: 'pence/litre';
    history: Array<{
        date: string;
        pricePence: number;
    }>;
    points: Array<{
        date: string;
        pricePence: number;
        lowPence: number;
        highPence: number;
        confidence?: 'low' | 'medium';
        signals?: Array<{
            name: 'pump' | 'b7h' | 'crude' | 'baseline';
            label: string;
            weight?: number;
            contributionPence: number;
            detail: string;
            available: boolean;
        }>;
    }>;
    warnings: Array<string>;
};

export type PhoneNumber = {
    /**
     * UK mobile in E.164 format, e.g. +447700900123
     */
    phoneNumber: string;
};

export type VerifyPhone = PhoneNumber & {
    code: string;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetHealthResponses = {
    /**
     * Worker is running
     */
    200: {
        status: 'ok';
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetForecastData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/forecast';
};

export type GetForecastErrors = {
    /**
     * Malformed or invalid request
     */
    400: ApiError;
    /**
     * Phone verification and a session cookie are required
     */
    401: ApiError;
    /**
     * Origin or credentials rejected
     */
    403: ApiError;
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Invalid input
     */
    422: ApiError;
    /**
     * Rate limit exceeded
     */
    429: ApiError;
    /**
     * Data unavailable or stale
     */
    503: ApiError;
};

export type GetForecastError = GetForecastErrors[keyof GetForecastErrors];

export type GetForecastResponses = {
    /**
     * Daily forecast and uncertainty range
     */
    200: Forecast;
};

export type GetForecastResponse = GetForecastResponses[keyof GetForecastResponses];

export type GetDemoDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/demo';
};

export type GetDemoDashboardErrors = {
    /**
     * Malformed or invalid request
     */
    400: ApiError;
    /**
     * Phone verification and a session cookie are required
     */
    401: ApiError;
    /**
     * Origin or credentials rejected
     */
    403: ApiError;
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Invalid input
     */
    422: ApiError;
    /**
     * Rate limit exceeded
     */
    429: ApiError;
    /**
     * Data unavailable or stale
     */
    503: ApiError;
};

export type GetDemoDashboardError = GetDemoDashboardErrors[keyof GetDemoDashboardErrors];

export type GetDemoDashboardResponses = {
    /**
     * Explicitly synthetic preview
     */
    200: Dashboard;
};

export type GetDemoDashboardResponse = GetDemoDashboardResponses[keyof GetDemoDashboardResponses];

export type GetDriverData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me/driver';
};

export type GetDriverErrors = {
    /**
     * Malformed or invalid request
     */
    400: ApiError;
    /**
     * Phone verification and a session cookie are required
     */
    401: ApiError;
    /**
     * Origin or credentials rejected
     */
    403: ApiError;
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Invalid input
     */
    422: ApiError;
    /**
     * Rate limit exceeded
     */
    429: ApiError;
    /**
     * Data unavailable or stale
     */
    503: ApiError;
};

export type GetDriverError = GetDriverErrors[keyof GetDriverErrors];

export type GetDriverResponses = {
    /**
     * Your latest reported tank state
     */
    200: Driver;
};

export type GetDriverResponse = GetDriverResponses[keyof GetDriverResponses];

export type SaveDriverData = {
    body: DriverInput;
    path?: never;
    query?: never;
    url: '/api/v1/me/driver';
};

export type SaveDriverErrors = {
    /**
     * Malformed or invalid request
     */
    400: ApiError;
    /**
     * Phone verification and a session cookie are required
     */
    401: ApiError;
    /**
     * Origin or credentials rejected
     */
    403: ApiError;
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Invalid input
     */
    422: ApiError;
    /**
     * Rate limit exceeded
     */
    429: ApiError;
    /**
     * Data unavailable or stale
     */
    503: ApiError;
};

export type SaveDriverError = SaveDriverErrors[keyof SaveDriverErrors];

export type SaveDriverResponses = {
    /**
     * Saved car with a fresh tank reading
     */
    200: Driver;
};

export type SaveDriverResponse = SaveDriverResponses[keyof SaveDriverResponses];

export type GetDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me/dashboard';
};

export type GetDashboardErrors = {
    /**
     * Malformed or invalid request
     */
    400: ApiError;
    /**
     * Phone verification and a session cookie are required
     */
    401: ApiError;
    /**
     * Origin or credentials rejected
     */
    403: ApiError;
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Invalid input
     */
    422: ApiError;
    /**
     * Rate limit exceeded
     */
    429: ApiError;
    /**
     * Data unavailable or stale
     */
    503: ApiError;
};

export type GetDashboardError = GetDashboardErrors[keyof GetDashboardErrors];

export type GetDashboardResponses = {
    /**
     * Personal forecast and recommendation
     */
    200: Dashboard;
};

export type GetDashboardResponse = GetDashboardResponses[keyof GetDashboardResponses];

export type GetRecommendationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me/recommendation';
};

export type GetRecommendationErrors = {
    /**
     * Malformed or invalid request
     */
    400: ApiError;
    /**
     * Phone verification and a session cookie are required
     */
    401: ApiError;
    /**
     * Origin or credentials rejected
     */
    403: ApiError;
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Invalid input
     */
    422: ApiError;
    /**
     * Rate limit exceeded
     */
    429: ApiError;
    /**
     * Data unavailable or stale
     */
    503: ApiError;
};

export type GetRecommendationError = GetRecommendationErrors[keyof GetRecommendationErrors];

export type GetRecommendationResponses = {
    /**
     * When to buy and how many litres
     */
    200: Recommendation;
};

export type GetRecommendationResponse = GetRecommendationResponses[keyof GetRecommendationResponses];

export type GetMessagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me/messages';
};

export type GetMessagesErrors = {
    /**
     * Malformed or invalid request
     */
    400: ApiError;
    /**
     * Phone verification and a session cookie are required
     */
    401: ApiError;
    /**
     * Origin or credentials rejected
     */
    403: ApiError;
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Invalid input
     */
    422: ApiError;
    /**
     * Rate limit exceeded
     */
    429: ApiError;
    /**
     * Data unavailable or stale
     */
    503: ApiError;
};

export type GetMessagesError = GetMessagesErrors[keyof GetMessagesErrors];

export type GetMessagesResponses = {
    /**
     * Your latest 20 fill-up messages; OTPs are never returned
     */
    200: Array<SmsMessage>;
};

export type GetMessagesResponse = GetMessagesResponses[keyof GetMessagesResponses];

export type IngestObservationsData = {
    body: MarketIngestion;
    path?: never;
    query?: never;
    url: '/api/v1/market/observations';
};

export type IngestObservationsErrors = {
    /**
     * Malformed or invalid request
     */
    400: ApiError;
    /**
     * Phone verification and a session cookie are required
     */
    401: ApiError;
    /**
     * Origin or credentials rejected
     */
    403: ApiError;
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Invalid input
     */
    422: ApiError;
    /**
     * Rate limit exceeded
     */
    429: ApiError;
    /**
     * Data unavailable or stale
     */
    503: ApiError;
};

export type IngestObservationsError = IngestObservationsErrors[keyof IngestObservationsErrors];

export type IngestObservationsResponses = {
    /**
     * Atomic, idempotent upsert by source and date
     */
    200: {
        accepted: number;
        source: string;
    };
};

export type IngestObservationsResponse = IngestObservationsResponses[keyof IngestObservationsResponses];

export type EvaluateAlertsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/alerts/evaluate';
};

export type EvaluateAlertsErrors = {
    /**
     * Malformed or invalid request
     */
    400: ApiError;
    /**
     * Phone verification and a session cookie are required
     */
    401: ApiError;
    /**
     * Origin or credentials rejected
     */
    403: ApiError;
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Invalid input
     */
    422: ApiError;
    /**
     * Rate limit exceeded
     */
    429: ApiError;
    /**
     * Data unavailable or stale
     */
    503: ApiError;
};

export type EvaluateAlertsError = EvaluateAlertsErrors[keyof EvaluateAlertsErrors];

export type EvaluateAlertsResponses = {
    /**
     * Daily deduplicated SMS evaluation
     */
    200: {
        checked: number;
        stubbed: number;
    };
};

export type EvaluateAlertsResponse = EvaluateAlertsResponses[keyof EvaluateAlertsResponses];

export type GetNearbyStationsData = {
    body?: never;
    path?: never;
    query: {
        latitude: number;
        longitude?: number | null;
    };
    url: '/api/v1/me/stations/nearby';
};

export type GetNearbyStationsErrors = {
    /**
     * Malformed or invalid request
     */
    400: ApiError;
    /**
     * Phone verification and a session cookie are required
     */
    401: ApiError;
    /**
     * Origin or credentials rejected
     */
    403: ApiError;
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Invalid input
     */
    422: ApiError;
    /**
     * Rate limit exceeded
     */
    429: ApiError;
    /**
     * Data unavailable or stale
     */
    503: ApiError;
};

export type GetNearbyStationsError = GetNearbyStationsErrors[keyof GetNearbyStationsErrors];

export type GetNearbyStationsResponses = {
    /**
     * Nearby stations ordered by distance
     */
    200: NearbyStations;
};

export type GetNearbyStationsResponse = GetNearbyStationsResponses[keyof GetNearbyStationsResponses];

export type GetTrackedStationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me/stations';
};

export type GetTrackedStationsErrors = {
    /**
     * Malformed or invalid request
     */
    400: ApiError;
    /**
     * Phone verification and a session cookie are required
     */
    401: ApiError;
    /**
     * Origin or credentials rejected
     */
    403: ApiError;
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Invalid input
     */
    422: ApiError;
    /**
     * Rate limit exceeded
     */
    429: ApiError;
    /**
     * Data unavailable or stale
     */
    503: ApiError;
};

export type GetTrackedStationsError = GetTrackedStationsErrors[keyof GetTrackedStationsErrors];

export type GetTrackedStationsResponses = {
    /**
     * History begins when a station is first tracked; missing history is never invented
     */
    200: TrackedStations;
};

export type GetTrackedStationsResponse = GetTrackedStationsResponses[keyof GetTrackedStationsResponses];

export type SaveOnboardingData = {
    body: OnboardingInput;
    path?: never;
    query?: never;
    url: '/api/v1/me/onboarding';
};

export type SaveOnboardingErrors = {
    /**
     * Malformed or invalid request
     */
    400: ApiError;
    /**
     * Phone verification and a session cookie are required
     */
    401: ApiError;
    /**
     * Origin or credentials rejected
     */
    403: ApiError;
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Invalid input
     */
    422: ApiError;
    /**
     * Rate limit exceeded
     */
    429: ApiError;
    /**
     * Data unavailable or stale
     */
    503: ApiError;
};

export type SaveOnboardingError = SaveOnboardingErrors[keyof SaveOnboardingErrors];

export type SaveOnboardingResponses = {
    /**
     * Onboarding complete
     */
    200: Driver;
};

export type SaveOnboardingResponse = SaveOnboardingResponses[keyof SaveOnboardingResponses];

export type UpdateTankData = {
    body: TankInput;
    path?: never;
    query?: never;
    url: '/api/v1/me/tank';
};

export type UpdateTankErrors = {
    /**
     * Malformed or invalid request
     */
    400: ApiError;
    /**
     * Phone verification and a session cookie are required
     */
    401: ApiError;
    /**
     * Origin or credentials rejected
     */
    403: ApiError;
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Invalid input
     */
    422: ApiError;
    /**
     * Rate limit exceeded
     */
    429: ApiError;
    /**
     * Data unavailable or stale
     */
    503: ApiError;
};

export type UpdateTankError = UpdateTankErrors[keyof UpdateTankErrors];

export type UpdateTankResponses = {
    /**
     * Updated tank reading
     */
    200: Driver;
};

export type UpdateTankResponse = UpdateTankResponses[keyof UpdateTankResponses];

export type SyncDataData = {
    body?: never;
    path: {
        kind: 'daily' | 'hourly' | 'models';
    };
    query?: never;
    url: '/api/v1/data/sync/{kind}';
};

export type SyncDataErrors = {
    /**
     * Malformed or invalid request
     */
    400: ApiError;
    /**
     * Phone verification and a session cookie are required
     */
    401: ApiError;
    /**
     * Origin or credentials rejected
     */
    403: ApiError;
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Invalid input
     */
    422: ApiError;
    /**
     * Rate limit exceeded
     */
    429: ApiError;
    /**
     * Data unavailable or stale
     */
    503: ApiError;
};

export type SyncDataError = SyncDataErrors[keyof SyncDataErrors];

export type SyncDataResponses = {
    /**
     * Job result
     */
    200: {
        key: string;
        skipped: boolean;
        [key: string]: unknown;
    };
};

export type SyncDataResponse = SyncDataResponses[keyof SyncDataResponses];

export type GetWeeklyOutlookData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/forecast/weekly';
};

export type GetWeeklyOutlookErrors = {
    /**
     * Data unavailable or stale
     */
    503: ApiError;
};

export type GetWeeklyOutlookError = GetWeeklyOutlookErrors[keyof GetWeeklyOutlookErrors];

export type GetWeeklyOutlookResponses = {
    /**
     * Next two official weekly observations; never a daily forecast
     */
    200: WeeklyOutlook;
};

export type GetWeeklyOutlookResponse = GetWeeklyOutlookResponses[keyof GetWeeklyOutlookResponses];

export type SendPhoneOtpData = {
    body: PhoneNumber;
    path?: never;
    query?: never;
    url: '/api/auth/phone-number/send-otp';
};

export type SendPhoneOtpErrors = {
    /**
     * Invalid code or phone number
     */
    400: {
        code: string;
        message: string;
    };
    /**
     * Too many attempts
     */
    429: {
        code: string;
        message: string;
    };
};

export type SendPhoneOtpError = SendPhoneOtpErrors[keyof SendPhoneOtpErrors];

export type SendPhoneOtpResponses = {
    /**
     * Better Auth result; verification sets an HttpOnly cookie
     */
    200: {
        status?: boolean;
        token?: string;
        user?: unknown;
    };
};

export type SendPhoneOtpResponse = SendPhoneOtpResponses[keyof SendPhoneOtpResponses];

export type VerifyPhoneOtpData = {
    body: VerifyPhone;
    path?: never;
    query?: never;
    url: '/api/auth/phone-number/verify';
};

export type VerifyPhoneOtpErrors = {
    /**
     * Invalid code or phone number
     */
    400: {
        code: string;
        message: string;
    };
    /**
     * Too many attempts
     */
    429: {
        code: string;
        message: string;
    };
};

export type VerifyPhoneOtpError = VerifyPhoneOtpErrors[keyof VerifyPhoneOtpErrors];

export type VerifyPhoneOtpResponses = {
    /**
     * Better Auth result; verification sets an HttpOnly cookie
     */
    200: {
        status?: boolean;
        token?: string;
        user?: unknown;
    };
};

export type VerifyPhoneOtpResponse = VerifyPhoneOtpResponses[keyof VerifyPhoneOtpResponses];

export type GetSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/get-session';
};

export type GetSessionResponses = {
    /**
     * Better Auth session or null
     */
    200: unknown;
};

export type SignOutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/sign-out';
};

export type SignOutResponses = {
    /**
     * Session revoked
     */
    200: {
        success: boolean;
    };
};

export type SignOutResponse = SignOutResponses[keyof SignOutResponses];
